spring.application.name=AI Powered Healthcare Dashboard
# Cloud Database Configuration
spring.datasource.url=jdbc:postgresql://db.yeewxyuzdeimzegqmyao.supabase.co:5432/postgres?
spring.datasource.username=postgres
spring.datasource.password=balaji123bj123

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Critical for Cloud: Prevent connection timeouts
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.show-sql=true
spring.ai.google.genai.api-key=AIzaSyA7oEKmE6mCoAv3jDVg8N8P7d0PbFPlwdc
server.port=8081
spring.ai.google.genai.chat.options.model=gemini-1.5-flash
logging.level.org.springframework.ai=DEBUG
spring.ai.google.genai.chat.options.safety-settings.HATE=BLOCK_NONE
spring.ai.google.genai.chat.options.safety-settings.HARASSMENT=BLOCK_NONE
spring.ai.google.genai.chat.options.safety-settings.MEDICAL=BLOCK_NONE
spring.sql.init.mode=always
