package com.example.demo.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.example.demo.model.Vitals; // Ensure this matches your package
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.List;

@Service
public class PdfService {

    public byte[] generateHealthReport(List<Vitals> vitalsList) {
        Document document = new Document(PageSize.A4);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter.getInstance(document, out);
            document.open();

            // 1. Title & Header
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18);
            Paragraph title = new Paragraph("AI HEALTHCARE - LONGITUDINAL REPORT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            if (vitalsList == null || vitalsList.isEmpty()) {
                document.add(new Paragraph("No health records found for this patient."));
            } else {
                // 2. Patient Info (Extracting ID from the first record)
                document.add(new Paragraph("Patient ID: " + vitalsList.get(0).getPatientId()));
                document.add(new Paragraph("Report Generated on: " + java.time.LocalDate.now()));
                document.add(new Paragraph(" ")); // Spacer

                // 3. Create Table (4 Columns to match your JSON)
                PdfPTable table = new PdfPTable(4);
                table.setWidthPercentage(100);
                table.setSpacingBefore(10f);
                table.setSpacingAfter(10f);

                // Table Headers
                table.addCell("Date/Time");
                table.addCell("Blood Pressure");
                table.addCell("Heart Rate (BPM)");
                table.addCell("AI Analysis Insight");

                // 4. Fill Table with your JSON Data
                for (Vitals v : vitalsList) {
                    table.addCell(v.getTimestamp() != null ? v.getTimestamp().toString() : "N/A");
                    table.addCell(v.getBloodPressure());
                    table.addCell(String.valueOf(v.getHeartRate()));
                    table.addCell(v.getAiInsight());
                }

                document.add(table);
            }

            // 5. Footer Disclaimer
            document.add(new Paragraph("\nNote: This report is generated by an AI Healthcare System. " +
                                     "Please consult a human doctor for medical verification."));

            document.close();
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        return out.toByteArray();
    }
}
